/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/home/yupix/Desktop/Github/ayuki_blog/lib/layouts/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5e28203c",
    path: "/posts/2019/01/19/categories-and-tags.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-5e28203c").then(next)
    },
  },
  {
    path: "/_posts/2019-01-19-categories-and-tags.html",
    redirect: "/posts/2019/01/19/categories-and-tags.html"
  },
  {
    name: "v-6bf36b5e",
    path: "/posts/2019/01/20/disable-comments.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6bf36b5e").then(next)
    },
  },
  {
    path: "/_posts/2019-01-20-disable-comments.html",
    redirect: "/posts/2019/01/20/disable-comments.html"
  },
  {
    name: "v-75f15674",
    path: "/posts/2019/02/01/demo-blogs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-75f15674").then(next)
    },
  },
  {
    path: "/_posts/2019-02-01-demo-blogs.html",
    redirect: "/posts/2019/02/01/demo-blogs.html"
  },
  {
    name: "v-433601d4",
    path: "/posts/2019/02/26/theme-guide-zh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-433601d4").then(next)
    },
  },
  {
    path: "/_posts/2019-02-26-theme-guide-zh.html",
    redirect: "/posts/2019/02/26/theme-guide-zh.html"
  },
  {
    name: "v-f2833ec0",
    path: "/posts/2019/02/27/theme-guide-en.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-f2833ec0").then(next)
    },
  },
  {
    path: "/_posts/2019-02-27-theme-guide-en.html",
    redirect: "/posts/2019/02/27/theme-guide-en.html"
  },
  {
    name: "v-0584b69e",
    path: "/posts/2019/03/22/header-config-zh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-0584b69e").then(next)
    },
  },
  {
    path: "/_posts/2019-03-22-header-config-zh.html",
    redirect: "/posts/2019/03/22/header-config-zh.html"
  },
  {
    name: "v-c03ea92c",
    path: "/posts/2019/03/23/header-config-en.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-c03ea92c").then(next)
    },
  },
  {
    path: "/_posts/2019-03-23-header-config-en.html",
    redirect: "/posts/2019/03/23/header-config-en.html"
  },
  {
    name: "v-9d849b3c",
    path: "/posts/2019/11/19/draft.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-9d849b3c").then(next)
    },
  },
  {
    path: "/_posts/2019-11-19-draft.html",
    redirect: "/posts/2019/11/19/draft.html"
  },
  {
    name: "v-506bf6d1",
    path: "/custom-pages/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("CustomPages", "v-506bf6d1").then(next)
    },
  },
  {
    path: "/custom-pages/index.html",
    redirect: "/custom-pages/"
  },
  {
    name: "v-b2754d56",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Home", "v-b2754d56").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-1f814451",
    path: "/posts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Posts", "v-1f814451").then(next)
    },
  },
  {
    path: "/posts/index.html",
    redirect: "/posts/"
  },
  {
    name: "v-03721585",
    path: "/posts/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-03721585").then(next)
    },
  },
  {
    path: "/posts/tags/index.html",
    redirect: "/posts/tags/"
  },
  {
    name: "v-5eb9e6bc",
    path: "/posts/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Categories", "v-5eb9e6bc").then(next)
    },
  },
  {
    path: "/posts/categories/index.html",
    redirect: "/posts/categories/"
  },
  {
    name: "v-cee70e46",
    path: "/posts/tags/ja.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-cee70e46").then(next)
    },
    meta: {"tagName":"ja"}
  },
  {
    name: "v-210b50ee",
    path: "/posts/tags/Steam.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-210b50ee").then(next)
    },
    meta: {"tagName":"Steam"}
  },
  {
    name: "v-f9a86400",
    path: "/posts/tags/archlinux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-f9a86400").then(next)
    },
    meta: {"tagName":"archlinux"}
  },
  {
    name: "v-b3875eaa",
    path: "/posts/tags/en.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b3875eaa").then(next)
    },
    meta: {"tagName":"en"}
  },
  {
    name: "v-1a3bcd74",
    path: "/posts/tags/zh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1a3bcd74").then(next)
    },
    meta: {"tagName":"zh"}
  },
  {
    name: "v-13441fa0",
    path: "/posts/tags/pt.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-13441fa0").then(next)
    },
    meta: {"tagName":"pt"}
  },
  {
    name: "v-b36151c6",
    path: "/posts/tags/draft.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-b36151c6").then(next)
    },
    meta: {"tagName":"draft"}
  },
  {
    name: "v-6b408274",
    path: "/posts/categories/demo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6b408274").then(next)
    },
    meta: {"categoryName":"demo"}
  },
  {
    name: "v-6fe1551c",
    path: "/posts/categories/docs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6fe1551c").then(next)
    },
    meta: {"categoryName":"docs"}
  },
  {
    name: "v-3ddfcdfa",
    path: "/posts/categories/draft.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3ddfcdfa").then(next)
    },
    meta: {"categoryName":"draft"}
  },
  {
    path: '*',
    component: GlobalLayout
  }
]