/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "vuepress-theme-meteorlxy",
  "description": "Vuepress theme of meteorlxy's blog",
  "base": "/",
  "pages": [
    {
      "title": "Categories and Tags",
      "frontmatter": {
        "category": "demo",
        "tags": [
          "en"
        ],
        "date": "2019-01-19T00:00:00.000Z",
        "title": "Categories and Tags",
        "vssue-id": 10,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2019-01-19-categories-and-tags.html",
      "relativePath": "_posts/2019-01-19-categories-and-tags.md",
      "key": "v-5e28203c",
      "path": "/posts/2019/01/19/categories-and-tags.html",
      "excerpt": "<p>Demo of how to set categories and tags.</p>\n",
      "type": "post",
      "top": false,
      "tags": [
        "en"
      ],
      "category": "demo",
      "createdAt": "2019-01-19",
      "updatedAt": null
    },
    {
      "title": "Disable Comments",
      "frontmatter": {
        "category": "demo",
        "tags": [
          "en"
        ],
        "date": "2019-01-20T00:00:00.000Z",
        "title": "Disable Comments",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2019-01-20-disable-comments.html",
      "relativePath": "_posts/2019-01-20-disable-comments.md",
      "key": "v-6bf36b5e",
      "path": "/posts/2019/01/20/disable-comments.html",
      "excerpt": "<p>Demo of how to disable comments.</p>\n",
      "type": "post",
      "top": false,
      "tags": [
        "en"
      ],
      "category": "demo",
      "createdAt": "2019-01-20",
      "updatedAt": null
    },
    {
      "title": "Blogs that use this theme",
      "frontmatter": {
        "top": 3,
        "category": "demo",
        "tags": [
          "en",
          "zh",
          "pt"
        ],
        "date": "2019-02-01T00:00:00.000Z",
        "title": "Blogs that use this theme",
        "vssue-id": 10,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2019-02-01-demo-blogs.html",
      "relativePath": "_posts/2019-02-01-demo-blogs.md",
      "key": "v-75f15674",
      "path": "/posts/2019/02/01/demo-blogs.html",
      "headers": [
        {
          "level": 2,
          "title": "English Blogs",
          "slug": "english-blogs"
        },
        {
          "level": 2,
          "title": "中文博客",
          "slug": "中文博客"
        },
        {
          "level": 2,
          "title": "Portuguese Blogs",
          "slug": "portuguese-blogs"
        }
      ],
      "excerpt": "<p>List of blogs that use this theme.</p>\n",
      "type": "post",
      "top": 3,
      "tags": [
        "en",
        "zh",
        "pt"
      ],
      "category": "demo",
      "createdAt": "2019-02-01",
      "updatedAt": null
    },
    {
      "title": "主题使用指南",
      "frontmatter": {
        "top": 2,
        "category": "docs",
        "tags": [
          "zh"
        ],
        "date": "2019-02-26T00:00:00.000Z",
        "title": "主题使用指南",
        "lang": "zh-CN",
        "vssue-id": 2,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2019-02-26-theme-guide-zh.html",
      "relativePath": "_posts/2019-02-26-theme-guide-zh.md",
      "key": "v-433601d4",
      "path": "/posts/2019/02/26/theme-guide-zh.html",
      "headers": [
        {
          "level": 2,
          "title": "开始使用",
          "slug": "开始使用"
        },
        {
          "level": 3,
          "title": "安装主题",
          "slug": "安装主题"
        },
        {
          "level": 3,
          "title": "配置主题",
          "slug": "配置主题"
        },
        {
          "level": 3,
          "title": "开始写博客",
          "slug": "开始写博客"
        },
        {
          "level": 2,
          "title": "主题语言",
          "slug": "主题语言"
        },
        {
          "level": 3,
          "title": "引入预设的语言包",
          "slug": "引入预设的语言包"
        },
        {
          "level": 3,
          "title": "翻译成你自己的语言",
          "slug": "翻译成你自己的语言"
        },
        {
          "level": 3,
          "title": "覆盖语言包的某些翻译",
          "slug": "覆盖语言包的某些翻译"
        },
        {
          "level": 2,
          "title": "页面评论",
          "slug": "页面评论"
        },
        {
          "level": 3,
          "title": "配置评论功能",
          "slug": "配置评论功能"
        },
        {
          "level": 3,
          "title": "针对每篇博文单独配置",
          "slug": "针对每篇博文单独配置"
        },
        {
          "level": 3,
          "title": "禁用评论功能",
          "slug": "禁用评论功能"
        },
        {
          "level": 2,
          "title": "其他特性",
          "slug": "其他特性"
        },
        {
          "level": 3,
          "title": "置顶博文",
          "slug": "置顶博文"
        },
        {
          "level": 3,
          "title": "草稿博文",
          "slug": "草稿博文"
        },
        {
          "level": 3,
          "title": "居中语法",
          "slug": "居中语法"
        },
        {
          "level": 2,
          "title": "配置参考",
          "slug": "配置参考"
        },
        {
          "level": 3,
          "title": "样式变量",
          "slug": "样式变量"
        },
        {
          "level": 3,
          "title": "Frontmatter",
          "slug": "frontmatter"
        }
      ],
      "excerpt": "<p><code>vuepress-theme-meteorlxy</code> 主题使用指南</p>\n<p><img src=\"https://img.shields.io/npm/v/vuepress-theme-meteorlxy.svg?style=flat\" alt=\"\">\n<img src=\"https://img.shields.io/github/license/meteorlxy/vuepress-theme-meteorlxy.svg?style=flat\" alt=\"\">\n<img src=\"https://img.shields.io/github/stars/meteorlxy/vuepress-theme-meteorlxy?style=social\" alt=\"\"></p>\n",
      "type": "post",
      "top": 2,
      "tags": [
        "zh"
      ],
      "category": "docs",
      "createdAt": "2019-02-26",
      "updatedAt": null
    },
    {
      "title": "标题栏的设置",
      "frontmatter": {
        "category": "docs",
        "tags": [
          "zh"
        ],
        "date": "2019-03-22T00:00:00.000Z",
        "title": "标题栏的设置",
        "lang": "zh-CN",
        "header-image": [
          "/assets/img/header-image-01.jpg",
          "/assets/img/header-image-02.jpg",
          "/assets/img/header-image-03.jpg"
        ],
        "header-title": true,
        "vssue-id": 2,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2019-03-22-header-config-zh.html",
      "relativePath": "_posts/2019-03-22-header-config-zh.md",
      "key": "v-0584b69e",
      "path": "/posts/2019/03/22/header-config-zh.html",
      "headers": [
        {
          "level": 2,
          "title": "博客的名称(theme-title)",
          "slug": "博客的名称-theme-title"
        },
        {
          "level": 2,
          "title": "导航栏页面(theme-nav)",
          "slug": "导航栏页面-theme-nav"
        },
        {
          "level": 2,
          "title": "页面小标题(header-title)",
          "slug": "页面小标题-header-title"
        },
        {
          "level": 2,
          "title": "标题背景图(header-image)",
          "slug": "标题背景图-header-image"
        }
      ],
      "excerpt": "<p>关于标题栏设置的详细教程</p>\n",
      "type": "post",
      "top": false,
      "tags": [
        "zh"
      ],
      "category": "docs",
      "createdAt": "2019-03-22",
      "updatedAt": null
    },
    {
      "title": "Theme Guide",
      "frontmatter": {
        "top": 1,
        "category": "docs",
        "tags": [
          "en"
        ],
        "date": "2019-02-27T00:00:00.000Z",
        "title": "Theme Guide",
        "vssue-id": 10,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2019-02-27-theme-guide-en.html",
      "relativePath": "_posts/2019-02-27-theme-guide-en.md",
      "key": "v-f2833ec0",
      "path": "/posts/2019/02/27/theme-guide-en.html",
      "headers": [
        {
          "level": 2,
          "title": "Getting Started",
          "slug": "getting-started"
        },
        {
          "level": 3,
          "title": "Installation",
          "slug": "installation"
        },
        {
          "level": 3,
          "title": "Config the theme",
          "slug": "config-the-theme"
        },
        {
          "level": 3,
          "title": "Write your posts",
          "slug": "write-your-posts"
        },
        {
          "level": 2,
          "title": "Theme Language",
          "slug": "theme-language"
        },
        {
          "level": 3,
          "title": "Introduce the language pack",
          "slug": "introduce-the-language-pack"
        },
        {
          "level": 3,
          "title": "Translate to your own language",
          "slug": "translate-to-your-own-language"
        },
        {
          "level": 3,
          "title": "Override the language packs",
          "slug": "override-the-language-packs"
        },
        {
          "level": 2,
          "title": "Posts Comments",
          "slug": "posts-comments"
        },
        {
          "level": 3,
          "title": "Config comments",
          "slug": "config-comments"
        },
        {
          "level": 3,
          "title": "Config for a single post",
          "slug": "config-for-a-single-post"
        },
        {
          "level": 3,
          "title": "Disable comments",
          "slug": "disable-comments"
        },
        {
          "level": 2,
          "title": "Other features",
          "slug": "other-features"
        },
        {
          "level": 3,
          "title": "Top post",
          "slug": "top-post"
        },
        {
          "level": 3,
          "title": "Draft post",
          "slug": "draft-post"
        },
        {
          "level": 3,
          "title": "Center syntax",
          "slug": "center-syntax"
        },
        {
          "level": 2,
          "title": "References",
          "slug": "references"
        },
        {
          "level": 3,
          "title": "Style variables",
          "slug": "style-variables"
        },
        {
          "level": 3,
          "title": "Frontmatter",
          "slug": "frontmatter"
        }
      ],
      "excerpt": "<p>Guide of <code>vuepress-theme-meteorlxy</code>.</p>\n<p><img src=\"https://img.shields.io/npm/v/vuepress-theme-meteorlxy.svg?style=flat\" alt=\"\">\n<img src=\"https://img.shields.io/github/license/meteorlxy/vuepress-theme-meteorlxy.svg?style=flat\" alt=\"\">\n<img src=\"https://img.shields.io/github/stars/meteorlxy/vuepress-theme-meteorlxy?style=social\" alt=\"\"></p>\n",
      "type": "post",
      "top": 1,
      "tags": [
        "en"
      ],
      "category": "docs",
      "createdAt": "2019-02-27",
      "updatedAt": null
    },
    {
      "title": "Header Config",
      "frontmatter": {
        "category": "docs",
        "tags": [
          "en"
        ],
        "date": "2019-03-23T00:00:00.000Z",
        "title": "Header Config",
        "header-image": [
          "/assets/img/header-image-01.jpg",
          "/assets/img/header-image-02.jpg",
          "/assets/img/header-image-03.jpg"
        ],
        "header-title": false,
        "vssue-id": 10,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2019-03-23-header-config-en.html",
      "relativePath": "_posts/2019-03-23-header-config-en.md",
      "key": "v-c03ea92c",
      "path": "/posts/2019/03/23/header-config-en.html",
      "headers": [
        {
          "level": 2,
          "title": "Theme Title",
          "slug": "theme-title"
        },
        {
          "level": 2,
          "title": "Theme Navigation",
          "slug": "theme-navigation"
        },
        {
          "level": 2,
          "title": "Header Title",
          "slug": "header-title"
        },
        {
          "level": 2,
          "title": "Header Image",
          "slug": "header-image"
        }
      ],
      "excerpt": "<p>Detailed guide for header config</p>\n",
      "type": "post",
      "top": false,
      "tags": [
        "en"
      ],
      "category": "docs",
      "createdAt": "2019-03-23",
      "updatedAt": null
    },
    {
      "title": "Draft",
      "frontmatter": {
        "draft": true,
        "category": "draft",
        "tags": [
          "draft"
        ],
        "date": "2019-11-19T00:00:00.000Z",
        "title": "Draft",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html"
      },
      "regularPath": "/_posts/2019-11-19-draft.html",
      "relativePath": "_posts/2019-11-19-draft.md",
      "key": "v-9d849b3c",
      "path": "/posts/2019/11/19/draft.html",
      "excerpt": "<p>This is a draft post, which will be included in <code>dev</code> mode, and be excluded in <code>build</code> mode.</p>\n",
      "type": "post",
      "top": false,
      "tags": [
        "draft"
      ],
      "category": "draft",
      "createdAt": "2019-11-19",
      "updatedAt": null
    },
    {
      "title": "Reference - Custom Pages",
      "frontmatter": {
        "layout": "CustomPages",
        "title": "Reference - Custom Pages",
        "aside": false
      },
      "regularPath": "/custom-pages/",
      "relativePath": "custom-pages/index.md",
      "key": "v-506bf6d1",
      "path": "/custom-pages/",
      "headers": [
        {
          "level": 2,
          "title": "Add more pages",
          "slug": "add-more-pages"
        },
        {
          "level": 2,
          "title": "Custom Layout",
          "slug": "custom-layout"
        }
      ],
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Home",
        "layout": "Home"
      },
      "regularPath": "/",
      "key": "v-b2754d56",
      "path": "/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Posts",
        "layout": "Posts"
      },
      "regularPath": "/posts/",
      "key": "v-1f814451",
      "path": "/posts/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Tags",
        "layout": "Tags"
      },
      "regularPath": "/posts/tags/",
      "key": "v-03721585",
      "path": "/posts/tags/"
    },
    {
      "frontmatter": {
        "title": "Categories",
        "layout": "Categories"
      },
      "regularPath": "/posts/categories/",
      "key": "v-5eb9e6bc",
      "path": "/posts/categories/"
    },
    {
      "frontmatter": {
        "title": "en | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/en.html",
      "key": "v-b3875eaa",
      "path": "/posts/tags/en.html"
    },
    {
      "frontmatter": {
        "title": "zh | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/zh.html",
      "key": "v-1a3bcd74",
      "path": "/posts/tags/zh.html"
    },
    {
      "frontmatter": {
        "title": "pt | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/pt.html",
      "key": "v-13441fa0",
      "path": "/posts/tags/pt.html"
    },
    {
      "frontmatter": {
        "title": "draft | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/draft.html",
      "key": "v-b36151c6",
      "path": "/posts/tags/draft.html"
    },
    {
      "frontmatter": {
        "title": "demo | Category",
        "layout": "Category"
      },
      "regularPath": "/posts/categories/demo.html",
      "key": "v-6b408274",
      "path": "/posts/categories/demo.html"
    },
    {
      "frontmatter": {
        "title": "docs | Category",
        "layout": "Category"
      },
      "regularPath": "/posts/categories/docs.html",
      "key": "v-6fe1551c",
      "path": "/posts/categories/docs.html"
    },
    {
      "frontmatter": {
        "title": "draft | Category",
        "layout": "Category"
      },
      "regularPath": "/posts/categories/draft.html",
      "key": "v-3ddfcdfa",
      "path": "/posts/categories/draft.html"
    }
  ],
  "themeConfig": {
    "lang": {
      "home": "Home",
      "posts": "Posts",
      "category": "Category",
      "categories": "Categories",
      "tag": "Tag",
      "tags": "Tags",
      "allCategories": "All",
      "search": "Search",
      "searchHint": "Search in title and excerpt",
      "noRelatedPosts": "No related posts",
      "top": "Top",
      "createdAt": "Created",
      "updatedAt": "Updated",
      "prevPost": "Previous Post",
      "nextPost": "Next Post",
      "toc": "Table of Contents",
      "comments": "Comments",
      "notFound": "Oops ! The page is not here"
    },
    "personalInfo": {
      "nickname": "meteorlxy",
      "description": "Happy Coding<br/>Happy Life",
      "email": "meteor.lxy@foxmail.com",
      "location": "Shenzhen, China",
      "organization": "Tencent",
      "avatar": "https://www.meteorlxy.cn/assets/img/avatar.jpg",
      "sns": {
        "github": {
          "account": "meteorlxy",
          "link": "https://github.com/meteorlxy"
        },
        "facebook": {
          "account": "meteorlxy.cn",
          "link": "https://www.facebook.com/meteorlxy.cn"
        },
        "linkedin": {
          "account": "meteorlxy",
          "link": "http://www.linkedin.com/in/meteorlxy"
        },
        "twitter": {
          "account": "meteorlxy_cn",
          "link": "https://twitter.com/meteorlxy_cn"
        },
        "weibo": {
          "account": "@焦炭君_Meteor",
          "link": "https://weibo.com/u/2039655434"
        },
        "zhihu": {
          "account": "meteorlxy.cn",
          "link": "https://www.zhihu.com/people/meteorlxy.cn"
        },
        "douban": {
          "account": "159342708",
          "link": "https://www.douban.com/people/159342708"
        },
        "reddit": {
          "account": "meteorlxy",
          "link": "https://www.reddit.com/user/meteorlxy"
        },
        "medium": {
          "account": "meteorlxy.cn",
          "link": "https://medium.com/@meteorlxy.cn"
        },
        "instagram": {
          "account": "meteorlxy.cn",
          "link": "https://www.instagram.com/meteorlxy.cn"
        },
        "gitlab": {
          "account": "meteorlxy",
          "link": "https://gitlab.com/meteorlxy"
        },
        "bitbucket": {
          "account": "meteorlxy",
          "link": "https://bitbucket.org/meteorlxy"
        },
        "docker": {
          "account": "meteorlxy",
          "link": "https://hub.docker.com/u/meteorlxy"
        },
        "csdn": {
          "account": "",
          "link": "https://www.csdn.net/"
        },
        "juejin": {
          "account": "meteorlxy",
          "link": "https://juejin.im/user/5c6fa9dde51d453fcb7baf09"
        }
      }
    },
    "header": {
      "background": {
        "useGeo": true
      },
      "showTitle": true
    },
    "footer": {
      "poweredBy": true,
      "poweredByTheme": true,
      "custom": "Copyright 2018-present <a href=\"https://github.com/meteorlxy\" target=\"_blank\">meteorlxy</a> | MIT License"
    },
    "infoCard": {
      "headerBackground": {
        "useGeo": true
      }
    },
    "lastUpdated": true,
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "exact": true
      },
      {
        "text": "Posts",
        "link": "/posts/",
        "exact": false
      },
      {
        "text": "Custom Pages",
        "link": "/custom-pages/",
        "exact": false
      },
      {
        "text": "Changelog",
        "link": "https://github.com/meteorlxy/vuepress-theme-meteorlxy/blob/master/CHANGELOG.md"
      },
      {
        "text": "Github",
        "link": "https://github.com/meteorlxy/vuepress-theme-meteorlxy"
      }
    ],
    "comments": {
      "owner": "meteorlxy",
      "repo": "vuepress-theme-meteorlxy",
      "clientId": "cbda894952ba70c00666",
      "clientSecret": "1ade785ca693bf3092be5e5338720d5ee43672b7",
      "autoCreateIssue": false
    },
    "pagination": {
      "perPage": 5
    },
    "defaultPages": {},
    "plugins": {}
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "path": "/"
    }
  }
}