/**
 * Generated by "@vuepress/plugin-blog (meteorlxy modified version)"
 */
export default {
  "demo": {
    "path": "/posts/categories/demo.html",
    "pageKeys": [
      "v-5e28203c",
      "v-6bf36b5e",
      "v-75f15674"
    ]
  },
  "docs": {
    "path": "/posts/categories/docs.html",
    "pageKeys": [
      "v-433601d4",
      "v-f2833ec0",
      "v-0584b69e",
      "v-c03ea92c"
    ]
  },
  "draft": {
    "path": "/posts/categories/draft.html",
    "pageKeys": [
      "v-9d849b3c"
    ]
  }
}