/**
 * Generated by "@vuepress/plugin-blog (meteorlxy modified version)"
 */
export default {
  "ja": {
    "path": "/posts/tags/ja.html",
    "pageKeys": [
      "v-5e28203c"
    ]
  },
  "Steam": {
    "path": "/posts/tags/Steam.html",
    "pageKeys": [
      "v-5e28203c"
    ]
  },
  "archlinux": {
    "path": "/posts/tags/archlinux.html",
    "pageKeys": [
      "v-5e28203c"
    ]
  },
  "en": {
    "path": "/posts/tags/en.html",
    "pageKeys": [
      "v-6bf36b5e",
      "v-75f15674",
      "v-f2833ec0",
      "v-c03ea92c"
    ]
  },
  "zh": {
    "path": "/posts/tags/zh.html",
    "pageKeys": [
      "v-75f15674",
      "v-433601d4",
      "v-0584b69e"
    ]
  },
  "pt": {
    "path": "/posts/tags/pt.html",
    "pageKeys": [
      "v-75f15674"
    ]
  },
  "draft": {
    "path": "/posts/tags/draft.html",
    "pageKeys": [
      "v-9d849b3c"
    ]
  }
}